server:
  port: 8080

spring:
  application:
    name: notify-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:2}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    port: 8081

notify:
  cron:
    reminder: ${NOTIFY_CRON_REMINDER:0 0 10 * * *}
    sell: ${NOTIFY_CRON_SELL:0 0 11 * * *}
    soldout: ${NOTIFY_CRON_SOLDOUT:0 0 12 * * *}
    leftPercent: ${NOTIFY_CRON_LEFT:0 0 13 * * *}
