server:
  port: 8080

spring:
  application:
    name: notify-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/microservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app123}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  server:
    port: 8081


